.\" $Header: /cvsroot/wxmaxima/wxmaxima/debian/wxmaxima.1,v 1.3 2005/11/21 22:44:32 zufus Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed \-e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "WXMAXIMA" "1" 
.SH "NAME" 
wxmaxima \- wxWidgets interface for Maxima
.SH "SYNOPSIS" 
.PP 
\fBwxmaxima\fR [-v] [-h] [-o <str>] [-e] [-b] [--logtostdout] [--pipe] [--exit-on-error] [-f <str>] [-u <str>] [-l <str>] [-X <str>] [-m <str>] [input file...]
.SH "DESCRIPTION" 
.PP 
\fBwxmaxima\fR is a rather self-explanatory graphical
front-end to the Maxima computer algebra system. It
provides a graphical interface and 2D formatted output display
for Maxima. Its menu system facilitates the access to a huge part of
the Maxima native set of commands and also to a browsable Maxima
help. The dialogue windows make easy the introduction of
mathematical entities such as limits, matrices, etc. Besides that
it extends Maxima with a few powerful features like the ability to
create diagrams with one parameter bound to a slider gui control.
.PP
Maxima is a free (GPL) common lisp implementation based of the
original computer algebra system Macsyma developed at MIT. It
has full documentation (HTML and info) included.
.PP
wxMaxima uses the cross-platform GUI toolkit wxWidgets and
runs natively on many operative systems.

.SH "OPTIONS"
.TP
.I \-h, \-\-help
Help: prints a list of options.

.TP
.I \-v, \-\-version
Prints the current version.

.TP
.I \-b, \-\-batch
processes the file, saves it afterwards. Will halt if wxMaxima finds an
error message in Maxima's output and pause if Maxima asks a question.

.TP
.I \-o, \-\-open=<str>
Open a file at startup.

.TP
.I \-e, \-\-eval=<str>
Evaluate the file after opening it.

.TP
.I \-\-logtostdout
Log all "debug messages" sidebar messages to stderr, too.

.TP
.I \-\-pipe
Pipe messages from Maxima to stdout.

.TP
.I \-\-exit-on-error
Close the program on any Maxima error.

.TP
.I \-f, --ini=<str>
Allows to specify a file to store the configuration in

.TP
.I \-u, \-\-use-version=<str>
Use Maxima version <str>.

.TP
.I \-l, \-\-lisp=<str>
Use a Maxima compiled with lisp compiler <str>.

.TP
.I \-X, \-\-extra-args=<str>
Allows to specify extra Maxima arguments

.TP
.I \-m, \-\-maxima=<str>
allows to specify the location of the Maxima binary

.SH BUGS
If you find a bug in wxMaxima, please report it in the wxMaxima bug database at
.LP
https://github.com/wxMaxima-developers/wxmaxima/issues
.LP
(Please check first, if it was not already reported.) And if you have a fix,
that would be great. wxMaxima is an open source project, where you can contribute.

If the issue is a mathematical bug, it might be a bug in Maxima (the
backend, which does the mathematical computations), not wxMaxima
(the graphical frontend).

The Maxima bug database is available at
.LP
https://sourceforge.net/p/maxima/bugs/
.LP

.SH OTHER INFO
The website of wxMaxima is https://wxmaxima-developers.github.io/wxmaxima/

Much documentation and tutorials can be found at
https://wxmaxima-developers.github.io/wxmaxima/help.html

.SH "SEE ALSO" 
.PP 
maxima (1), xmaxima (1).

.SH "AUTHORS"
.PP

.IP \[bu] 2
J. Rafael Rodriguez Galvan (Debian project), original author of the manual page
.IP \[bu]
Gunter Königsmann (wxMaxima project)
.IP \[bu]
Wolfgang Dautermannn (wxMaxima project)

.PP
Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 or any later version
published by the Free Software Foundation.
 
