#include "EventIDs.h"
#include <wx/utils.h>
const EventIDs::EventId EventIDs::menu_pane_hideall(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_math(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_history(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_structure(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_xmlInspector(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_format(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_greek(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_unicode(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_log(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_variables(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_draw(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_help(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_symbols(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_stats(wxNewId());
const EventIDs::EventId EventIDs::menu_pane_dockAll(wxNewId());
const EventIDs::EventId EventIDs::input_line_id(wxNewId());
const EventIDs::EventId EventIDs::refresh_id(wxNewId());
const EventIDs::EventId EventIDs::menu_batch_id(wxNewId());
const EventIDs::EventId EventIDs::menu_load_id(wxNewId());
const EventIDs::EventId EventIDs::menu_sconsole_id(wxNewId());
const EventIDs::EventId EventIDs::menu_interrupt_id(wxNewId());
const EventIDs::EventId EventIDs::menu_solve(wxNewId());
const EventIDs::EventId EventIDs::menu_solve_to_poly(wxNewId());
const EventIDs::EventId EventIDs::menu_solve_num(wxNewId());
const EventIDs::EventId EventIDs::menu_allroots(wxNewId());
const EventIDs::EventId EventIDs::menu_bfallroots(wxNewId());
const EventIDs::EventId EventIDs::menu_realroots(wxNewId());
const EventIDs::EventId EventIDs::menu_solve_lin(wxNewId());
const EventIDs::EventId EventIDs::menu_solve_algsys(wxNewId());
const EventIDs::EventId EventIDs::menu_eliminate(wxNewId());
const EventIDs::EventId EventIDs::menu_solve_ode(wxNewId());
const EventIDs::EventId EventIDs::menu_ivp_1(wxNewId());
const EventIDs::EventId EventIDs::menu_ivp_2(wxNewId());
const EventIDs::EventId EventIDs::menu_rk(wxNewId());
const EventIDs::EventId EventIDs::menu_bvp(wxNewId());
const EventIDs::EventId EventIDs::menu_genmatrix(wxNewId());
const EventIDs::EventId EventIDs::menu_gen_mat(wxNewId());
const EventIDs::EventId EventIDs::menu_gen_mat_lambda(wxNewId());
const EventIDs::EventId EventIDs::menu_enter_mat(wxNewId());
const EventIDs::EventId EventIDs::menu_csv2mat(wxNewId());
const EventIDs::EventId EventIDs::menu_mat2csv(wxNewId());
const EventIDs::EventId EventIDs::menu_csv2list(wxNewId());
const EventIDs::EventId EventIDs::menu_list2csv(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_row(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_col(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_row_list(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_col_list(wxNewId());
const EventIDs::EventId EventIDs::menu_submatrix(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_multiply(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_exponent(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_hadamard_product(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_hadamard_exponent(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_loadLapack(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dgeev_eigenvaluesOnly(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dgeev(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_zgeev_eigenvaluesOnly(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_zgeev(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dgeqrf(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dgesv(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dgesvd(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dgesvd_valuesOnly(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dlange_max(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dlange_one(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dlange_inf(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_dlange_frobenius(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_zlange_max(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_zlange_one(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_zlange_inf(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_zlange_frobenius(wxNewId());
const EventIDs::EventId EventIDs::menu_matrix_zheev(wxNewId());
const EventIDs::EventId EventIDs::menu_invert_mat(wxNewId());
const EventIDs::EventId EventIDs::menu_cpoly(wxNewId());
const EventIDs::EventId EventIDs::menu_determinant(wxNewId());
const EventIDs::EventId EventIDs::menu_rank(wxNewId());
const EventIDs::EventId EventIDs::menu_eigen(wxNewId());
const EventIDs::EventId EventIDs::menu_eigvect(wxNewId());
const EventIDs::EventId EventIDs::menu_fun_def(wxNewId());
const EventIDs::EventId EventIDs::menu_gensym(wxNewId());
const EventIDs::EventId EventIDs::menu_adjoint_mat(wxNewId());
const EventIDs::EventId EventIDs::menu_transpose(wxNewId());
const EventIDs::EventId EventIDs::menu_map_mat(wxNewId());
const EventIDs::EventId EventIDs::menu_map(wxNewId());
const EventIDs::EventId EventIDs::menu_map_lambda(wxNewId());
const EventIDs::EventId EventIDs::menu_copymatrix(wxNewId());
const EventIDs::EventId EventIDs::menu_ratsimp(wxNewId());
const EventIDs::EventId EventIDs::menu_radsimp(wxNewId());
const EventIDs::EventId EventIDs::menu_scanmapfactor(wxNewId());
const EventIDs::EventId EventIDs::menu_factor(wxNewId());
const EventIDs::EventId EventIDs::menu_horner(wxNewId());
const EventIDs::EventId EventIDs::menu_collapse(wxNewId());
const EventIDs::EventId EventIDs::menu_optimize(wxNewId());
const EventIDs::EventId EventIDs::menu_mainvar(wxNewId());
const EventIDs::EventId EventIDs::menu_grind(wxNewId());
const EventIDs::EventId EventIDs::menu_gfactor(wxNewId());
const EventIDs::EventId EventIDs::menu_expand(wxNewId());
const EventIDs::EventId EventIDs::menu_expandwrt(wxNewId());
const EventIDs::EventId EventIDs::menu_expandwrt_denom(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_setposition(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_getposition(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_flush_output(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_flength(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_close(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_opena(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_openr(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_openw(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_printf(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_readline(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_readchar(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_readbyte(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_writebyte(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_charp(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_alphacharp(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_alphanumericp(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_digitcharp(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_constituent(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_uppercasep(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_lowercasep(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_create_ascii(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_cequal(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_cequalignore(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_clessp(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_clesspignore(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_cgreaterp(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_cgreaterpignore(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_sequal(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_sequalignore(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_ascii(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_cint(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_unicode(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_unicode_to_utf8(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_utf8_to_unicode(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_charat(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_charlist(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_simplode(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_sinsert(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_eval_string(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_parse_string(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_scopy(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_sdowncase(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_slength(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_smake(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_smismatch(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_split(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_sposition(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_sremove(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_sremovefirst(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_tokens(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_ssearch(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_ssort(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_ssubstfirst(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_strim(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_striml(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_strimr(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_number_to_octets(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_octets_to_number(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_octets_to_string(wxNewId());
const EventIDs::EventId EventIDs::menu_stringproc_string_to_octets(wxNewId());
const EventIDs::EventId EventIDs::menu_sregex_load(wxNewId());
const EventIDs::EventId EventIDs::menu_sregex_regex_compile(wxNewId());
const EventIDs::EventId EventIDs::menu_sregex_regex_match_pos(wxNewId());
const EventIDs::EventId EventIDs::menu_sregex_regex_match(wxNewId());
const EventIDs::EventId EventIDs::menu_sregex_regex_split(wxNewId());
const EventIDs::EventId EventIDs::menu_sregex_subst_first(wxNewId());
const EventIDs::EventId EventIDs::menu_sregex_regex_subst(wxNewId());
const EventIDs::EventId EventIDs::menu_sregex_string_to_regex(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_load(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_chdir(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_mkdir(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_rmdir(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_getcurrentdirectory(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_copy_file(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_rename_file(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_delete_file(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_getenv(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_directory(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_pathname_directory(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_pathname_name(wxNewId());
const EventIDs::EventId EventIDs::menu_opsyst_pathname_type(wxNewId());
const EventIDs::EventId EventIDs::menu_scsimp(wxNewId());
const EventIDs::EventId EventIDs::menu_xthru(wxNewId());
const EventIDs::EventId EventIDs::menu_talg(wxNewId());
const EventIDs::EventId EventIDs::menu_tellrat(wxNewId());
const EventIDs::EventId EventIDs::menu_modulus(wxNewId());
const EventIDs::EventId EventIDs::menu_trigsimp(wxNewId());
const EventIDs::EventId EventIDs::menu_trigreduce(wxNewId());
const EventIDs::EventId EventIDs::menu_trigexpand(wxNewId());
const EventIDs::EventId EventIDs::menu_trigrat(wxNewId());
const EventIDs::EventId EventIDs::menu_rectform(wxNewId());
const EventIDs::EventId EventIDs::menu_polarform(wxNewId());
const EventIDs::EventId EventIDs::menu_demoivre(wxNewId());
const EventIDs::EventId EventIDs::menu_exponentialize(wxNewId());
const EventIDs::EventId EventIDs::menu_num_out(wxNewId());
const EventIDs::EventId EventIDs::menu_stringdisp(wxNewId());
const EventIDs::EventId EventIDs::menu_to_float(wxNewId());
const EventIDs::EventId EventIDs::menu_to_bfloat(wxNewId());
const EventIDs::EventId EventIDs::menu_to_numer(wxNewId());
const EventIDs::EventId EventIDs::menu_rat(wxNewId());
const EventIDs::EventId EventIDs::menu_rationalize(wxNewId());
const EventIDs::EventId EventIDs::menu_guess_exact_value(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qag(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qags(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qagi(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qawc(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qawf_sin(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qawf_cos(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qawo_sin(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qawo_cos(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qaws1(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qaws2(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qaws3(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qaws4(wxNewId());
const EventIDs::EventId EventIDs::menu_quad_qagp(wxNewId());
const EventIDs::EventId EventIDs::menu_num_domain(wxNewId());
const EventIDs::EventId EventIDs::menu_set_precision(wxNewId());
const EventIDs::EventId EventIDs::menu_set_displayprecision(wxNewId());
const EventIDs::EventId EventIDs::menu_engineeringFormat(wxNewId());
const EventIDs::EventId EventIDs::menu_engineeringFormatSetup(wxNewId());
const EventIDs::EventId EventIDs::menu_functions(wxNewId());
const EventIDs::EventId EventIDs::menu_variables(wxNewId());
const EventIDs::EventId EventIDs::menu_arrays(wxNewId());
const EventIDs::EventId EventIDs::menu_macros(wxNewId());
const EventIDs::EventId EventIDs::menu_labels(wxNewId());
const EventIDs::EventId EventIDs::menu_myoptions(wxNewId());
const EventIDs::EventId EventIDs::menu_rules(wxNewId());
const EventIDs::EventId EventIDs::menu_aliases(wxNewId());
const EventIDs::EventId EventIDs::menu_structs(wxNewId());
const EventIDs::EventId EventIDs::menu_dependencies(wxNewId());
const EventIDs::EventId EventIDs::menu_gradefs(wxNewId());
const EventIDs::EventId EventIDs::menu_let_rule_packages(wxNewId());
const EventIDs::EventId EventIDs::menu_maxima_uses_internal_help(wxNewId());
const EventIDs::EventId EventIDs::menu_maxima_uses_html_help(wxNewId());
const EventIDs::EventId EventIDs::menu_maxima_uses_wxmaxima_help(wxNewId());
const EventIDs::EventId EventIDs::menu_goto_url(wxNewId());
const EventIDs::EventId EventIDs::menu_clear_var(wxNewId());
const EventIDs::EventId EventIDs::menu_clear_fun(wxNewId());
const EventIDs::EventId EventIDs::menu_kill(wxNewId());
const EventIDs::EventId EventIDs::menu_integrate(wxNewId());
const EventIDs::EventId EventIDs::menu_risch(wxNewId());
const EventIDs::EventId EventIDs::menu_laplace(wxNewId());
const EventIDs::EventId EventIDs::menu_ilt(wxNewId());
const EventIDs::EventId EventIDs::menu_continued_fraction(wxNewId());
const EventIDs::EventId EventIDs::menu_gcd(wxNewId());
const EventIDs::EventId EventIDs::menu_lcm(wxNewId());
const EventIDs::EventId EventIDs::menu_divide(wxNewId());
const EventIDs::EventId EventIDs::menu_partfrac(wxNewId());
const EventIDs::EventId EventIDs::menu_sum(wxNewId());
const EventIDs::EventId EventIDs::menu_simpsum(wxNewId());
const EventIDs::EventId EventIDs::menu_limit(wxNewId());
const EventIDs::EventId EventIDs::menu_lbfgs(wxNewId());
const EventIDs::EventId EventIDs::menu_taylor(wxNewId());
const EventIDs::EventId EventIDs::menu_powerseries(wxNewId());
const EventIDs::EventId EventIDs::menu_fourier(wxNewId());
const EventIDs::EventId EventIDs::menu_pade(wxNewId());
const EventIDs::EventId EventIDs::menu_diff(wxNewId());
const EventIDs::EventId EventIDs::menu_solve_de(wxNewId());
const EventIDs::EventId EventIDs::menu_atvalue(wxNewId());
const EventIDs::EventId EventIDs::menu_lhs(wxNewId());
const EventIDs::EventId EventIDs::menu_rhs(wxNewId());
const EventIDs::EventId EventIDs::menu_wxmaximahelp(wxNewId());
const EventIDs::EventId EventIDs::menu_maximahelp(wxNewId());
const EventIDs::EventId EventIDs::menu_example(wxNewId());
const EventIDs::EventId EventIDs::menu_apropos(wxNewId());
const EventIDs::EventId EventIDs::menu_product(wxNewId());
const EventIDs::EventId EventIDs::menu_time(wxNewId());
const EventIDs::EventId EventIDs::menu_factsimp(wxNewId());
const EventIDs::EventId EventIDs::menu_factcomb(wxNewId());
const EventIDs::EventId EventIDs::menu_realpart(wxNewId());
const EventIDs::EventId EventIDs::menu_imagpart(wxNewId());
const EventIDs::EventId EventIDs::menu_subst(wxNewId());
const EventIDs::EventId EventIDs::menu_psubst(wxNewId());
const EventIDs::EventId EventIDs::menu_ratsubst(wxNewId());
const EventIDs::EventId EventIDs::menu_fullratsubst(wxNewId());
const EventIDs::EventId EventIDs::menu_at(wxNewId());
const EventIDs::EventId EventIDs::menu_substinpart(wxNewId());
const EventIDs::EventId EventIDs::menu_opsubst(wxNewId());
const EventIDs::EventId EventIDs::menu_jumptoerror(wxNewId());
const EventIDs::EventId EventIDs::menu_math_as_1D_ASCII(wxNewId());
const EventIDs::EventId EventIDs::menu_math_as_2D_ASCII(wxNewId());
const EventIDs::EventId EventIDs::menu_math_as_graphics(wxNewId());
const EventIDs::EventId EventIDs::menu_logexpand_false(wxNewId());
const EventIDs::EventId EventIDs::menu_logexpand_true(wxNewId());
const EventIDs::EventId EventIDs::menu_logexpand_all(wxNewId());
const EventIDs::EventId EventIDs::menu_logexpand_super(wxNewId());
const EventIDs::EventId EventIDs::menu_noAutosubscript(wxNewId());
const EventIDs::EventId EventIDs::menu_defaultAutosubscript(wxNewId());
const EventIDs::EventId EventIDs::menu_alwaysAutosubscript(wxNewId());
const EventIDs::EventId EventIDs::menu_autosubscriptIndividual(wxNewId());
const EventIDs::EventId EventIDs::menu_declareAutosubscript(wxNewId());
const EventIDs::EventId EventIDs::menu_noAutosubscriptIndividual(wxNewId());
const EventIDs::EventId EventIDs::menu_roundedMatrixParens(wxNewId());
const EventIDs::EventId EventIDs::menu_squareMatrixParens(wxNewId());
const EventIDs::EventId EventIDs::menu_straightMatrixParens(wxNewId());
const EventIDs::EventId EventIDs::menu_angledMatrixParens(wxNewId());
const EventIDs::EventId EventIDs::menu_noMatrixParens(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_2d(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_3d(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_explicit(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_implicit(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_parametric(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_points(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_fgcolor(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_fillcolor(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_title(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_key(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_grid(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_axis(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_accuracy(wxNewId());
const EventIDs::EventId EventIDs::menu_draw_contour(wxNewId());
const EventIDs::EventId EventIDs::menu_license(wxNewId());
const EventIDs::EventId EventIDs::menu_changelog(wxNewId());
const EventIDs::EventId EventIDs::button_factor_id(wxNewId());
const EventIDs::EventId EventIDs::button_solve(wxNewId());
const EventIDs::EventId EventIDs::button_solve_ode(wxNewId());
const EventIDs::EventId EventIDs::button_limit(wxNewId());
const EventIDs::EventId EventIDs::button_taylor(wxNewId());
const EventIDs::EventId EventIDs::button_expand(wxNewId());
const EventIDs::EventId EventIDs::button_ratsimp(wxNewId());
const EventIDs::EventId EventIDs::button_radcan(wxNewId());
const EventIDs::EventId EventIDs::button_trigsimp(wxNewId());
const EventIDs::EventId EventIDs::button_trigexpand(wxNewId());
const EventIDs::EventId EventIDs::button_trigreduce(wxNewId());
const EventIDs::EventId EventIDs::button_trigrat(wxNewId());
const EventIDs::EventId EventIDs::button_integrate(wxNewId());
const EventIDs::EventId EventIDs::button_diff(wxNewId());
const EventIDs::EventId EventIDs::button_sum(wxNewId());
const EventIDs::EventId EventIDs::button_product(wxNewId());
const EventIDs::EventId EventIDs::button_button_constant(wxNewId());
const EventIDs::EventId EventIDs::button_factor(wxNewId());
const EventIDs::EventId EventIDs::button_subst(wxNewId());
const EventIDs::EventId EventIDs::button_plot2(wxNewId());
const EventIDs::EventId EventIDs::button_plot3(wxNewId());
const EventIDs::EventId EventIDs::button_rectform(wxNewId());
const EventIDs::EventId EventIDs::button_map(wxNewId());
const EventIDs::EventId EventIDs::gp_plot2(wxNewId());
const EventIDs::EventId EventIDs::gp_plot3(wxNewId());
const EventIDs::EventId EventIDs::menu_animationautostart(wxNewId());
const EventIDs::EventId EventIDs::menu_animationframerate(wxNewId());
const EventIDs::EventId EventIDs::menu_display(wxNewId());
const EventIDs::EventId EventIDs::menu_soft_restart(wxNewId());
const EventIDs::EventId EventIDs::menu_plot_format(wxNewId());
const EventIDs::EventId EventIDs::menu_build_info(wxNewId());
const EventIDs::EventId EventIDs::menu_bug_report(wxNewId());
const EventIDs::EventId EventIDs::menu_add_path(wxNewId());
const EventIDs::EventId EventIDs::menu_evaluate_all_visible(wxNewId());
const EventIDs::EventId EventIDs::menu_evaluate_all(wxNewId());
const EventIDs::EventId EventIDs::menu_show_tip(wxNewId());
const EventIDs::EventId EventIDs::menu_copy_matlab_from_worksheet(wxNewId());
const EventIDs::EventId EventIDs::menu_copy_tex_from_worksheet(wxNewId());
const EventIDs::EventId EventIDs::menu_copy_text_from_worksheet(wxNewId());
const EventIDs::EventId EventIDs::menu_logcontract(wxNewId());
const EventIDs::EventId EventIDs::menu_logexpand(wxNewId());
const EventIDs::EventId EventIDs::menu_to_fact(wxNewId());
const EventIDs::EventId EventIDs::menu_to_gamma(wxNewId());
const EventIDs::EventId EventIDs::menu_texform(wxNewId());
const EventIDs::EventId EventIDs::menu_debugmode(wxNewId());
const EventIDs::EventId EventIDs::menu_debugmode_off(wxNewId());
const EventIDs::EventId EventIDs::menu_debugmode_lisp(wxNewId());
const EventIDs::EventId EventIDs::menu_debugmode_all(wxNewId());
const EventIDs::EventId EventIDs::menu_for(wxNewId());
const EventIDs::EventId EventIDs::menu_while(wxNewId());
const EventIDs::EventId EventIDs::menu_block(wxNewId());
const EventIDs::EventId EventIDs::menu_block_noLocal(wxNewId());
const EventIDs::EventId EventIDs::menu_local(wxNewId());
const EventIDs::EventId EventIDs::menu_return(wxNewId());
const EventIDs::EventId EventIDs::menu_trace(wxNewId());
const EventIDs::EventId EventIDs::menu_lambda(wxNewId());
const EventIDs::EventId EventIDs::menu_quotequote(wxNewId());
const EventIDs::EventId EventIDs::menu_quote(wxNewId());
const EventIDs::EventId EventIDs::menu_quoteblock(wxNewId());
const EventIDs::EventId EventIDs::menu_def_fun(wxNewId());
const EventIDs::EventId EventIDs::menu_def_macro(wxNewId());
const EventIDs::EventId EventIDs::menu_def_variable(wxNewId());
const EventIDs::EventId EventIDs::menu_compile(wxNewId());
const EventIDs::EventId EventIDs::menu_paramType(wxNewId());
const EventIDs::EventId EventIDs::menu_structdef(wxNewId());
const EventIDs::EventId EventIDs::menu_structnew(wxNewId());
const EventIDs::EventId EventIDs::menu_structuse(wxNewId());
const EventIDs::EventId EventIDs::menu_saveLisp(wxNewId());
const EventIDs::EventId EventIDs::menu_loadLisp(wxNewId());
const EventIDs::EventId EventIDs::menu_maximatostring(wxNewId());
const EventIDs::EventId EventIDs::menu_stringtomaxima(wxNewId());
const EventIDs::EventId EventIDs::button_enter(wxNewId());
const EventIDs::EventId EventIDs::menu_zoom_80(wxNewId());
const EventIDs::EventId EventIDs::menu_zoom_120(wxNewId());
const EventIDs::EventId EventIDs::menu_zoom_150(wxNewId());
const EventIDs::EventId EventIDs::menu_zoom_200(wxNewId());
const EventIDs::EventId EventIDs::menu_zoom_300(wxNewId());
const EventIDs::EventId EventIDs::menu_copy_as_bitmap(wxNewId());
const EventIDs::EventId EventIDs::menu_copy_as_svg(wxNewId());
const EventIDs::EventId EventIDs::menu_save_as_svg(wxNewId());
const EventIDs::EventId EventIDs::menu_copy_as_emf(wxNewId());
const EventIDs::EventId EventIDs::menu_save_as_emf(wxNewId());
const EventIDs::EventId EventIDs::menu_copy_as_rtf(wxNewId());
const EventIDs::EventId EventIDs::menu_copy_to_file(wxNewId());
const EventIDs::EventId EventIDs::menu_export_html(wxNewId());
const EventIDs::EventId EventIDs::menu_change_var(wxNewId());
const EventIDs::EventId EventIDs::menu_change_var_evaluate(wxNewId());
const EventIDs::EventId EventIDs::menu_nouns(wxNewId());
const EventIDs::EventId EventIDs::menu_evaluate(wxNewId());
const EventIDs::EventId EventIDs::menu_convert_to_code(wxNewId());
const EventIDs::EventId EventIDs::menu_add_comment(wxNewId());
const EventIDs::EventId EventIDs::menu_convert_to_comment(wxNewId());
const EventIDs::EventId EventIDs::menu_add_subsubsection(wxNewId());
const EventIDs::EventId EventIDs::menu_add_heading5(wxNewId());
const EventIDs::EventId EventIDs::menu_add_heading6(wxNewId());
const EventIDs::EventId EventIDs::menu_convert_to_subsubsection(wxNewId());
const EventIDs::EventId EventIDs::menu_convert_to_heading5(wxNewId());
const EventIDs::EventId EventIDs::menu_convert_to_heading6(wxNewId());
const EventIDs::EventId EventIDs::menu_add_subsection(wxNewId());
const EventIDs::EventId EventIDs::menu_convert_to_subsection(wxNewId());
const EventIDs::EventId EventIDs::menu_add_section(wxNewId());
const EventIDs::EventId EventIDs::menu_convert_to_section(wxNewId());
const EventIDs::EventId EventIDs::menu_add_title(wxNewId());
const EventIDs::EventId EventIDs::menu_convert_to_title(wxNewId());
const EventIDs::EventId EventIDs::menu_add_pagebreak(wxNewId());
const EventIDs::EventId EventIDs::menu_fold_all_cells(wxNewId());
const EventIDs::EventId EventIDs::menu_unfold_all_cells(wxNewId());
const EventIDs::EventId EventIDs::menu_insert_input(wxNewId());
const EventIDs::EventId EventIDs::menu_insert_previous_input(wxNewId());
const EventIDs::EventId EventIDs::menu_insert_previous_output(wxNewId());
const EventIDs::EventId EventIDs::menu_autocomplete(wxNewId());
const EventIDs::EventId EventIDs::menu_autocomplete_templates(wxNewId());
const EventIDs::EventId EventIDs::menu_paste_input(wxNewId());
const EventIDs::EventId EventIDs::menu_fullscreen(wxNewId());
const EventIDs::EventId EventIDs::menu_remove_output(wxNewId());
const EventIDs::EventId EventIDs::menu_list_create_from_elements(wxNewId());
const EventIDs::EventId EventIDs::menu_list_create_from_rule(wxNewId());
const EventIDs::EventId EventIDs::menu_list_create_from_list(wxNewId());
const EventIDs::EventId EventIDs::menu_list_create_from_args(wxNewId());
const EventIDs::EventId EventIDs::menu_list_list2matrix(wxNewId());
const EventIDs::EventId EventIDs::menu_list_matrix2list(wxNewId());
const EventIDs::EventId EventIDs::menu_list_actual_values_storage(wxNewId());
const EventIDs::EventId EventIDs::menu_list_sort(wxNewId());
const EventIDs::EventId EventIDs::menu_list_remove_duplicates(wxNewId());
const EventIDs::EventId EventIDs::menu_list_length(wxNewId());
const EventIDs::EventId EventIDs::menu_list_push(wxNewId());
const EventIDs::EventId EventIDs::menu_list_pop(wxNewId());
const EventIDs::EventId EventIDs::menu_list_reverse(wxNewId());
const EventIDs::EventId EventIDs::menu_list_first(wxNewId());
const EventIDs::EventId EventIDs::menu_list_last(wxNewId());
const EventIDs::EventId EventIDs::menu_list_lastn(wxNewId());
const EventIDs::EventId EventIDs::menu_list_rest(wxNewId());
const EventIDs::EventId EventIDs::menu_list_restN(wxNewId());
const EventIDs::EventId EventIDs::menu_list_nth(wxNewId());
const EventIDs::EventId EventIDs::menu_list_map(wxNewId());
const EventIDs::EventId EventIDs::menu_list_use_actual_values(wxNewId());
const EventIDs::EventId EventIDs::menu_list_extract_value(wxNewId());
const EventIDs::EventId EventIDs::menu_list_as_function_arguments(wxNewId());
const EventIDs::EventId EventIDs::menu_list_do_for_each_element(wxNewId());
const EventIDs::EventId EventIDs::menu_list_remove_element(wxNewId());
const EventIDs::EventId EventIDs::menu_list_append_item_start(wxNewId());
const EventIDs::EventId EventIDs::menu_list_append_item_end(wxNewId());
const EventIDs::EventId EventIDs::menu_list_append_list(wxNewId());
const EventIDs::EventId EventIDs::menu_list_interleave(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_packages(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_0(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_1(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_2(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_3(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_4(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_5(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_6(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_7(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_8(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_9(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_10(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_11(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_12(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_13(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_14(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_15(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_16(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_17(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_18(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_19(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_20(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_21(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_22(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_23(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_24(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_25(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_26(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_27(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_28(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_package_29(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_documents(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_0(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_1(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_2(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_3(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_4(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_5(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_6(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_7(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_8(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_9(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_10(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_11(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_12(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_13(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_14(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_15(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_16(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_17(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_18(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_19(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_20(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_21(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_22(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_23(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_24(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_25(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_26(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_27(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_28(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_29(wxNewId());
const EventIDs::EventId EventIDs::menu_recent_document_separator(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_0(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_1(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_2(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_3(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_4(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_5(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_6(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_7(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_8(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_9(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_10(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_11(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_12(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_13(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_14(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_15(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_16(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_17(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_18(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_19(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_20(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_21(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_22(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_23(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_24(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_25(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_26(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_27(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_28(wxNewId());
const EventIDs::EventId EventIDs::menu_unsaved_document_29(wxNewId());
const EventIDs::EventId EventIDs::menu_construct_fraction(wxNewId());
const EventIDs::EventId EventIDs::menu_insert_image(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_mean(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_median(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_var(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_dev(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_tt1(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_tt2(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_tnorm(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_linreg(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_lsquares(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_histogram(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_scatterplot(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_barsplot(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_piechart(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_boxplot(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_readm(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_enterm(wxNewId());
const EventIDs::EventId EventIDs::menu_stats_subsample(wxNewId());
const EventIDs::EventId EventIDs::menu_format_code(wxNewId());
const EventIDs::EventId EventIDs::menu_format_text(wxNewId());
const EventIDs::EventId EventIDs::menu_format_heading6(wxNewId());
const EventIDs::EventId EventIDs::menu_format_heading5(wxNewId());
const EventIDs::EventId EventIDs::menu_format_subsubsection(wxNewId());
const EventIDs::EventId EventIDs::menu_format_subsection(wxNewId());
const EventIDs::EventId EventIDs::menu_format_section(wxNewId());
const EventIDs::EventId EventIDs::menu_format_title(wxNewId());
const EventIDs::EventId EventIDs::menu_format_image(wxNewId());
const EventIDs::EventId EventIDs::menu_format_pagebreak(wxNewId());
const EventIDs::EventId EventIDs::menu_help_tutorials(wxNewId());
const EventIDs::EventId EventIDs::menu_help_tutorials_start(wxNewId());
const EventIDs::EventId EventIDs::menu_help_solving(wxNewId());
const EventIDs::EventId EventIDs::menu_help_diffequations(wxNewId());
const EventIDs::EventId EventIDs::menu_help_numberformats(wxNewId());
const EventIDs::EventId EventIDs::menu_help_tolerances(wxNewId());
const EventIDs::EventId EventIDs::menu_help_listaccess(wxNewId());
const EventIDs::EventId EventIDs::menu_help_memoizing(wxNewId());
const EventIDs::EventId EventIDs::menu_help_3d(wxNewId());
const EventIDs::EventId EventIDs::menu_help_varnames(wxNewId());
const EventIDs::EventId EventIDs::menu_help_fittingData(wxNewId());
const EventIDs::EventId EventIDs::menu_help_tutorials_end(wxNewId());
const EventIDs::EventId EventIDs::menu_show_toolbar(wxNewId());
const EventIDs::EventId EventIDs::menu_history_previous(wxNewId());
const EventIDs::EventId EventIDs::menu_history_next(wxNewId());
const EventIDs::EventId EventIDs::menu_check_updates(wxNewId());
const EventIDs::EventId EventIDs::gentran_load(wxNewId());
const EventIDs::EventId EventIDs::gentran_lang_c(wxNewId());
const EventIDs::EventId EventIDs::gentran_lang_fortran(wxNewId());
const EventIDs::EventId EventIDs::gentran_lang_ratfor(wxNewId());
const EventIDs::EventId EventIDs::gentran_to_stdout(wxNewId());
const EventIDs::EventId EventIDs::gentran_to_file(wxNewId());
const EventIDs::EventId EventIDs::socket_client_id(wxNewId());
const EventIDs::EventId EventIDs::socket_server_id(wxNewId());
const EventIDs::EventId EventIDs::gnuplot_query_terminals_id(wxNewId());
const EventIDs::EventId EventIDs::menu_additionalSymbols(wxNewId());
const EventIDs::EventId EventIDs::enable_unicodePane(wxNewId());
const EventIDs::EventId EventIDs::menu_showLatinGreekLookalikes(wxNewId());
const EventIDs::EventId EventIDs::menu_showGreekMu(wxNewId());
const EventIDs::EventId EventIDs::menu_invertWorksheetBackground(wxNewId());
const EventIDs::EventId EventIDs:: popid_comment_selection(wxNewId());
const EventIDs::EventId EventIDs:: popid_divide_cell(wxNewId());
const EventIDs::EventId EventIDs:: popid_copy_image(wxNewId());
const EventIDs::EventId EventIDs:: popid_copy_animation(wxNewId());
const EventIDs::EventId EventIDs:: popid_copy_svg(wxNewId());
const EventIDs::EventId EventIDs:: popid_copy_emf(wxNewId());
const EventIDs::EventId EventIDs:: popid_copy_rtf(wxNewId());
const EventIDs::EventId EventIDs:: popid_add_watch(wxNewId());
const EventIDs::EventId EventIDs:: popid_add_watch_label(wxNewId());
const EventIDs::EventId EventIDs:: popid_special_constant_percent(wxNewId());
const EventIDs::EventId EventIDs:: popid_changeasterisk(wxNewId());
const EventIDs::EventId EventIDs:: popid_hideasterisk(wxNewId());
const EventIDs::EventId EventIDs:: popid_delete(wxNewId());
const EventIDs::EventId EventIDs:: popid_simplify(wxNewId());
const EventIDs::EventId EventIDs:: popid_expand(wxNewId());
const EventIDs::EventId EventIDs:: popid_factor(wxNewId());
const EventIDs::EventId EventIDs:: popid_solve(wxNewId());
const EventIDs::EventId EventIDs:: popid_solve_num(wxNewId());
const EventIDs::EventId EventIDs:: popid_integrate(wxNewId());
const EventIDs::EventId EventIDs:: popid_diff(wxNewId());
const EventIDs::EventId EventIDs:: popid_subst(wxNewId());
const EventIDs::EventId EventIDs:: popid_plot2d(wxNewId());
const EventIDs::EventId EventIDs:: popid_plot3d(wxNewId());
const EventIDs::EventId EventIDs:: popid_float(wxNewId());
const EventIDs::EventId EventIDs:: popid_edit(wxNewId());
const EventIDs::EventId EventIDs:: popid_add_comment(wxNewId());
const EventIDs::EventId EventIDs:: popid_insert_input(wxNewId());
const EventIDs::EventId EventIDs:: popid_copy_matlab(wxNewId());
const EventIDs::EventId EventIDs:: popid_copy_tex(wxNewId());
const EventIDs::EventId EventIDs:: popid_copy_text(wxNewId());
const EventIDs::EventId EventIDs:: popid_copy_mathml(wxNewId());
const EventIDs::EventId EventIDs:: popid_labels_disable(wxNewId());
const EventIDs::EventId EventIDs:: popid_labels_user(wxNewId());
const EventIDs::EventId EventIDs:: popid_labels_useronly(wxNewId());
const EventIDs::EventId EventIDs:: popid_labels_autogenerated(wxNewId());
const EventIDs::EventId EventIDs:: popid_labelwidth(wxNewId());
const EventIDs::EventId EventIDs:: popid_labelwidth3(wxNewId());
const EventIDs::EventId EventIDs:: popid_labelwidth4(wxNewId());
const EventIDs::EventId EventIDs:: popid_labelwidth5(wxNewId());
const EventIDs::EventId EventIDs:: popid_labelwidth6(wxNewId());
const EventIDs::EventId EventIDs:: popid_labelwidth7(wxNewId());
const EventIDs::EventId EventIDs:: popid_labelwidth8(wxNewId());
const EventIDs::EventId EventIDs:: popid_labelwidth9(wxNewId());
const EventIDs::EventId EventIDs:: popid_labelwidth10(wxNewId());
const EventIDs::EventId EventIDs:: popid_digits_20(wxNewId());
const EventIDs::EventId EventIDs:: popid_digits_50(wxNewId());
const EventIDs::EventId EventIDs:: popid_digits_100(wxNewId());
const EventIDs::EventId EventIDs:: popid_digits_all(wxNewId());
const EventIDs::EventId EventIDs:: popid_digits_all_linebreak(wxNewId());
const EventIDs::EventId EventIDs:: popid_image(wxNewId());
const EventIDs::EventId EventIDs:: popid_change_image(wxNewId());
const EventIDs::EventId EventIDs:: popid_svg(wxNewId());
const EventIDs::EventId EventIDs:: popid_emf(wxNewId());
const EventIDs::EventId EventIDs:: popid_animation_save(wxNewId());
const EventIDs::EventId EventIDs:: popid_animation_start(wxNewId());
const EventIDs::EventId EventIDs:: popid_evaluate(wxNewId());
const EventIDs::EventId EventIDs:: popid_evaluate_section(wxNewId());
const EventIDs::EventId EventIDs:: popid_merge_cells(wxNewId());
const EventIDs::EventId EventIDs:: popid_insert_text(wxNewId());
const EventIDs::EventId EventIDs:: popid_insert_title(wxNewId());
const EventIDs::EventId EventIDs:: popid_insert_section(wxNewId());
const EventIDs::EventId EventIDs:: popid_insert_subsection(wxNewId());
const EventIDs::EventId EventIDs:: popid_insert_subsubsection(wxNewId());
const EventIDs::EventId EventIDs:: popid_insert_heading5(wxNewId());
const EventIDs::EventId EventIDs:: popid_insert_heading6(wxNewId());
const EventIDs::EventId EventIDs:: popid_auto_answer(wxNewId());
const EventIDs::EventId EventIDs:: popid_never_autoanswer(wxNewId());
const EventIDs::EventId EventIDs:: popid_popup_gnuplot(wxNewId());
const EventIDs::EventId EventIDs:: popid_fold(wxNewId());
const EventIDs::EventId EventIDs:: popid_unfold(wxNewId());
const EventIDs::EventId EventIDs:: popid_maxsizechooser(wxNewId());
const EventIDs::EventId EventIDs:: popid_resolutionchooser(wxNewId());
const EventIDs::EventId EventIDs:: popid_reloadimage(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion1(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion2(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion3(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion4(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion5(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion6(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion7(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion8(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion9(wxNewId());
const EventIDs::EventId EventIDs:: popid_suggestion10(wxNewId());
const EventIDs::EventId EventIDs:: popid_hide_tooltipMarker(wxNewId());
const EventIDs::EventId EventIDs:: popid_hide_tooltipMarkerForThisMessage(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_real(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_imaginary(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_complex(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_additive(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_alphabetic(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_bindtest(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_antisymmetric(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_commutative(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_symmetric(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_constant(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_even(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_odd(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_evenfun(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_oddfun(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_increasing(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_decreasing(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_integer(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_noninteger(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_integervalued(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_lassociative(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_rassociative(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_linear(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_mainvar(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_multiplicative(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_nary(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_nonarray(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_nonscalar(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_scalar(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_noun(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_outative(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_posfun(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_rational(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_irrational(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_greaterThan(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_evfun(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_evflag(wxNewId());
const EventIDs::EventId EventIDs:: popid_property_atvalue(wxNewId());
