
file(READ "${INPUT_FILE}" FILE_CONTENTS)
string(REPLACE "nsvg" "wxm_nsvg" FILE_CONTENTS "${FILE_CONTENTS}")
string(REPLACE "NSVG" "wxm_NSVG" FILE_CONTENTS "${FILE_CONTENTS}")
string(REPLACE "nanosvg.h" "nanosvg_private.h" FILE_CONTENTS "${FILE_CONTENTS}")
# string(REPLACE "nsvg__parseXML" "wxm_nsvg__parseXML" FILE_CONTENTS "${FILE_CONTENTS}")
# string(REPLACE "nsvgCreate" "wxm_nsvgCreate" FILE_CONTENTS "${FILE_CONTENTS}")
# string(REPLACE "nsvgDelete" "wxm_nsvgDelete" FILE_CONTENTS "${FILE_CONTENTS}")
# string(REPLACE "nsvgDuplicatePath" "wxm_nsvgDuplicatePath" FILE_CONTENTS "${FILE_CONTENTS}")
# string(REPLACE "nsvgParse" "wxm_nsvgParse" FILE_CONTENTS "${FILE_CONTENTS}")
# string(REPLACE "NSVGimage" "wxm_NSVGimage" FILE_CONTENTS "${FILE_CONTENTS}")
# string(REPLACE "nsvgRasterize" "wxm_nsvgRasterize" FILE_CONTENTS "${FILE_CONTENTS}")
# string(REPLACE "NSVGRasterize" "wxm_NSVGRasterize" FILE_CONTENTS "${FILE_CONTENTS}")
# string(REPLACE "NSVGNamedColor" "wxm_NSVGNamedColor" FILE_CONTENTS "${FILE_CONTENTS}")
file(WRITE ${OUTPUT_FILE} "${FILE_CONTENTS}")
