//  SPDX-License-Identifier: GPL-2.0+
#ifndef WXM_VERSION_H
#define WXM_VERSION_H
#define WXMAXIMA_VERSION "@WXMAXIMA_VERSION@"
#define CMAKE_INSTALL_PREFIX "@CMAKE_INSTALL_PREFIX@"
#cmakedefine USE_PRECOMP_HEADER
#cmakedefine USE_WEBVIEW
#cmakedefine NANOSVG_CAUSES_NO_LINK_ERROR
#cmakedefine WXMAXIMA_GIT_SHORT_HASH "@WXMAXIMA_GIT_SHORT_HASH@"

#include <thread>
#ifdef __cpp_lib_jthread
    #define jthread std::jthread
#else
    #define jthread std::thread
#endif
#endif
