name: wxmaxima
version: 21.05.0
summary: A nightly build of wxMaxima, a gui for Maxima, a full-featured CAS.
description: wxMaxima is a quite full-featured graphical user interface for Maxima.
confinement: strict
grade: stable
icon: data/io.github.wxmaxima_developers.wxMaxima.svg

apps:
  wxmaxima:
    command: wxmaxima
    desktop: data/io.github.wxmaxima_developers.wxMaxima.desktop
    plugs:
     - network
     - network-bind
     - home
     - removable-media
     - optical-drive
     - process-control

parts:
  wxmaxima:
    plugin: cmake
    source: https://github.com/wxMaxima-developers/wxmaxima.git
    build-packages:
     - libwxbase3.0-dev
     - libwxgtk3.0-dev
     - gettext
    stage-packages:
     - maxima
     - maxima-doc
     - gnuplot
     - tcl-vtk6
     - python-vtk6
